Lab 4:  Introduction to Linear Algebra and Transformations

We have just started our section on Linear Algebra, so in this lab we will mainly focus on how to represent matrices in python, and how to do some of the basic matrix manipulations.  We will also play around with matrix transformations to see how they behave, and get some intuition before talking about them in class.

In [2]:
from PIL import Image  #This imports the Python Image Library (PIL).
import math   #Our usual module for extra math functions
import numpy as np   #This is the main module that we will be using today.  
#It allows us to create and manipulate matrices

get_ipython().magic('matplotlib inline')   #this is included to help make our plots appear right under the cell
import matplotlib.pyplot as plt            #this is the main plotting module

In [3]:
#declaring matrices with numpy
A_1 = np.array([[1,2],[3,4]])  #this is a 2x2 matrix.
#the first brackets (i.e. [1,2]) constitute the first row of the matrix, and similarly for the 
#second brackets ([3,4] second row)
#Be sure to have brackets around the whole thing ... [[1,2],[3,4]] in this example
print("A_1 = \n",A_1)
#you can also make column vectors (i.e. an nx1 matrix)
v_1 = np.array([[10],[7]])  #a 2x1 column matrix
print("v_1 = \n", v_1)

#To get the shape of a matrix (i.e. the number of rows and columns ... (r,c)) use .shape :
print("The shape of A_1 is ", A_1.shape)

#we can also make a few simple matrices without specifying each matrix entry:
Zeros = np.zeros( (2,3) )  #this create a 2x3 matrix whose entries are all zero
print("Zeros = \n", Zeros)
Ones = np.ones(v_1.shape)  #this creates a matix of all ones with the same shape as v_1
print("Ones = \n", Ones)
ID = np.eye(4)   #this creates an identity matrix of size 4x4 (it must be square)
print("Identity Matrix = \n", ID)

A_1 = 
 [[1 2]
 [3 4]]
v_1 = 
 [[10]
 [ 7]]
The shape of A_1 is  (2, 2)
Zeros = 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones = 
 [[1.]
 [1.]]
Identity Matrix = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
#Your Turn
#Create a 2x4 matrix whose entries are the first 8 prime numbers. Show that it has the correct shape.
R = np.array([[4,3],[2,1]])
print("The matrix is \n", R)

The matrix is 
 [[4 3]
 [2 1]]


In [5]:
#Simple matrix manipulations (addition, multiplication)
#to add or subtract matrices, just use the following (you can only do this for matrices of the same shape):
A_2 = np.array([[4,3],[2,1]])
A_3 = A_2 - A_1               #You just subtract or add the matrices with "-" or "+"
print("A_2 - A_1 = \n", A_3)

#To multiply matrices you need to use np.dot(Matrix1, Matrix2)
#using "*" is NOT the same!! This would multipy element-wise
A_4 = np.dot(A_1,A_2)
print("A_1 x A_2 = \n", A_4)

#You need to make sure that for AxB, the number of columns in A is equal to the number of rows in B
A_5 = np.dot(A_1,v_1)
print("A_1 x v_1 = \n", A_5)
#notice that we can compute np.dot(A_1,v_1) since A_1.shape = (2,2) and v_1.shape = (2,1), but
#np.dot(v_1,A_1) would give an error for miss-aligned shapes


A_2 - A_1 = 
 [[ 3  1]
 [-1 -3]]
A_1 x A_2 = 
 [[ 8  5]
 [20 13]]
A_1 x v_1 = 
 [[24]
 [58]]


In [ ]:
#Your Turn.  Modify this function to return a 2X2 rotation matrix for the given input angle
#feel free to go to the wikipedia page for "Rotation Matrix" to remind you of how it works
#and you can use the math module for math.cos() and math.sin()
def RotMat(theta):
    RM = np.array([[theta,theta],[theta,theta]])  #modify the entries here
    return RM

#test it out by creating a rotation matrix and multiplying it with a few column matrices
#(which represent points in the plane) to verify that it works.


In [ ]:
#Your Turn.  We can create a simple function to test if matrices commute
def Commutator(Ain,Bin):   #this returns the difference of the two matrices multiplied the two ways
    com = np.dot(Ain,Bin) - np.dot(Bin,Ain)
    return com

def DoCommute(Ain,Bin):  #this returns true if they commute and false if they do not
    com = Commutator(Ain,Bin)   #getting the commutator
    ZeroMat = np.zeros(Ain.shape)  #getting an appropriately sized zero matrix
    CVal = False
    if np.array_equal(com,ZeroMat):  #if they are equivalent, then Ain and Bin commute
        CVal = True
    return CVal

#try DoCommute out on a few random 2x2 matrices ... how hard is it to find matrices that commute?
#Do rotation matrices in 2D commute (create two different rotation matrices and apply the commutator)?
#Does the result you get make physical sense?  


In [ ]:
#Matrix Determinant, Transpose, and Inverse
#First the Transpose
A_6 = A_1.transpose()
print("The transpose of \n", A_1, "\n is \n", A_6)

#Now for the Determinant 
det1 = np.linalg.det(A_1)
print("The determinant of \n",A_1,"\n is \n", det1)

#And finally the inverse
A_7 = np.linalg.inv(A_1)
print("The inverse of \n", A_1, "\n is \n", A_7)

#and we can check that really is an inverse
A_8 = np.dot(A_1,A_7)
print(A_1, "\n times \n", A_7, "\n is \n", A_8)  #notice that it gives back the identity

In [ ]:
#Your Turn.  Solve the following system of equations by representing it in matrix form: A*x=b,
#and finding x = A^(-1)*b
# System of equations:  5x - 3y = 12 and 2x + y = -7


In [ ]:
#Matrices as transformations (in the plane).  We can think of the matrix equation A*x1 = x2 as a point in the plane (x1)
#being tranformed (via the 2x2 transformation matrix, A) to another point in the plane (x2).
#We would like to think about how transformation matrices tranform all the points in the plane.
#To do this we will consider the unit disk with the four quadrants colored differently.  
#Then we will see how different martices transform this image.

#First let's just see what the original, un-transformed, domain looks like
xpixels = 600  #the number of pixels in each line in the x-direction 
ypixels = 600  #the number of pixels in each column of the y-direction (total pixels = xpixels*ypixels)
xstart = -2    #the x-value of the first pixel
ystart = 2     #the y-value of the first pixel
xrange = 4     #how wide the domain is in the x-direction
yrange = 4     #how tall the domain is in the y-direction
dx = xrange/(xpixels-1)   #this specifies the distance between two neighboring points in the x direction
dy = yrange/(ypixels-1)   #this specifies the distance between two neighboring points in the y direction

SquareIm = Image.new("RGB", (xpixels,ypixels))  #This creates a new image (SquareIm) to which we will add pixels
for y_ind in range(0,ypixels):
    for x_ind in range(0,xpixels):
        x = xstart + dx*float(x_ind)  #the current x-value of the pixel we are considering
        y = ystart - dy*float(y_ind)  #the current y-vlaue of the pixel we are considering
        #if abs(x) > 1 or abs(y) > 1:   #the pixel is outside of the 2x2 square and will be colored white
        if x**2+y**2 > 1:    #the pixel is outside of the unit sphere and will be colored white
            SquareIm.putpixel((x_ind,y_ind), (255,255,255))
        else:      #the pixel is inside the unit disk and we need to determine which quadrant it is in
            if x > 0:
                if y > 0:
                    SquareIm.putpixel((x_ind,y_ind), (255,0,0))  #first quadrant will be red
                else:
                    SquareIm.putpixel((x_ind,y_ind), (0,0,255))  #fourth quadrant will be blue
            else:
                if y > 0:
                    SquareIm.putpixel((x_ind,y_ind), (255,255,0))  #second quadrant will be yellow
                else:
                    SquareIm.putpixel((x_ind,y_ind), (0,255,0))  #third quadrant will be green
                    
fig, ax = plt.subplots(figsize=(14,14))  #this sets the size of our image
ax.axis('equal')  #this ensures that the image will be a square here
ax.imshow(SquareIm,extent=[xstart,xstart+xrange,ystart-yrange,ystart])  #this shows the image with axes

In [ ]:
#Now let's see how a matrix transforms this image
A = np.array( [[-2**(-1/2),2**(-1/2)],[2**(-1/2),2**(-1/2)]] )  
#this is the matrix that you should change to see the effect of different transformations

#we will be using the inverse of this matrix to map points on a grid backward to see which color they land on
#in the above image ... The image that results will be the transform under A of the original image.
Ainv = np.linalg.inv(A)

#the number of pixels in each direction, and the domain specification are the same as in the previous image,
#so we will use the same variables

TransSquareIm = Image.new("RGB", (xpixels,ypixels))  #This creates a new image (TransSquareIm) to which we will add pixels
for y_ind in range(0,ypixels):
    for x_ind in range(0,xpixels):
        x = xstart + dx*float(x_ind)  #the current x-value of the pixel we are considering
        y = ystart - dy*float(y_ind)  #the current y-vlaue of the pixel we are considering
        
        XYcolvec = np.array( [[x],[y]])    #this creates a column vector (2x1 matrix) from the x and y values
        XYcolvecPrev = np.dot(Ainv,XYcolvec)  #this takes the matrix product 
        XPrev = XYcolvecPrev[0][0]         #taking the x value of the resultant column vector 
        YPrev = XYcolvecPrev[1][0]         #and similarly for the y-value
        #if abs(XPrev) > 1 or abs(YPrev) > 1:   #the pixel is outside of the 2x2 square and will be colored white
        if XPrev**2+YPrev**2 > 1:       #the pixel is outside of the unit disk and will be colored white
            TransSquareIm.putpixel((x_ind,y_ind), (255,255,255))
        else:      #the pixel is inside the unit disk and we need to determine which quadrant it is in
            if XPrev > 0:
                if YPrev > 0:
                    TransSquareIm.putpixel((x_ind,y_ind), (255,0,0))  #first quadrant will be red
                else:
                    TransSquareIm.putpixel((x_ind,y_ind), (0,0,255))  #fourth quadrant will be blue
            else:
                if YPrev > 0:
                    TransSquareIm.putpixel((x_ind,y_ind), (255,255,0))  #second quadrant will be yellow
                else:
                    TransSquareIm.putpixel((x_ind,y_ind), (0,255,0))  #third quadrant will be green
                    
fig2, ax2 = plt.subplots(figsize=(14,14))  #this sets the size of our image
ax2.axis('equal')     #this ensures that the image will be a square here
ax2.imshow(TransSquareIm,extent=[xstart,xstart+xrange,ystart-yrange,ystart])   #this shows the image with axes

In [ ]:
#Your turn.  Try out a number of different matrics in the above cell to get a good feeling for the different types of 
#transformations that are possible.  For each of the matrices that you try, record in comments below the following
#information: the determinant, and your qualitative observations (rotation, reflection, stretching, squeezing, larger,
#smaller, etc.)

#Do you see any links between the determinant and the qualitative type of transformation?